### ISSUE TITLE
希望guzzle能更新到7.*

### ISSUE THREAD

**Issue by aszx0413** [Miposent/fuiou-pay#1]
现在的项目是锁定了guzzle的版本为7.*，而且guzzle出v7也好久了，希望能用最新的

**Comment by Miposent** [comment]
好的，接收意见。下个版本增加[扫码商户入网接口]API，并进行更新

**Comment by Miposent** [comment]
> 现在的项目是锁定了guzzle的版本为7.*，而且guzzle出v7也好久了，希望能用最新的

接收意见。下个版本增加[扫码商户入网接口]API，并进行更新。

**Comment by jieer** [comment]
还没改，好多版本装不上

**Comment by Miposent** [comment]
> 
当前最新版本为2.0，已经是改成使用guzzle的版本为7.*，可以composer require miposent/fuiou-pay 2.0

**Comment by jieer** [comment]
Problem 1
    - Root composer.json requires miposent/fuiou-pay 2.0 -> satisfiable by miposent/fuiou-pay[2.0].
    - miposent/fuiou-pay 2.0 requires guzzlehttp/guzzle 7.4.0 -> found guzzlehttp/guzzle[7.4.0] but the package is fixed to 7.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by Miposent** [comment]
> Problem 1 - Root composer.json requires miposent/fuiou-pay 2.0 -> satisfiable by miposent/fuiou-pay[2.0]. - miposent/fuiou-pay 2.0 requires guzzlehttp/guzzle 7.4.0 -> found guzzlehttp/guzzle[7.4.0] but the package is fixed to 7.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

可以重新request一下，这边已对 guzzlehttp版本进行了优化
