### ISSUE TITLE
请问公钥和私钥应该怎么生成和获取到

### ISSUE THREAD

**Issue by aszx0413** [Miposent/fuiou-pay#2]
'private_key'  => 'xxxxxxxxxx',  //私钥
	'public_key'   => 'xxxxxxxxxx',  //公钥

**Comment by Miposent** [comment]
> ```
> 'private_key'  => 'xxxxxxxxxx',  //私钥
> 'public_key'   => 'xxxxxxxxxx',  //公钥
> ```

这块得找富友让其他提供；若你想先使用测试的话，在富友提供的文档中的"测试环境参数"中有提供测试的公钥和私钥
