### ISSUE TITLE
验签接口的BUG

### ISSUE THREAD

**Issue by hianghokung** [Miposent/fuiou-pay#3]
> public function checkVerify()
>     {
>         if (empty($this->response->sign)) {
>             return false;
>         }
>         $param = json_decode(json_encode($this->response), true);
>         unset($param['sign']);
>         $paramStr = $this->getParamStr($this->getIconParam($this->getFilterReserved($param)));
>         return openssl_verify($paramStr, base64_decode($this->response->sign), $this->getPublicKey(), OPENSSL_ALGO_MD5);
>     }

验签这里有BUG，$this->response值为数组，"$this->response->sign"该改为“$this->response['sign']”

**Comment by Miposent** [comment]
感谢提醒！
